sql

CREATE TABLE Payment ( 
PaymentID INT PRIMARY KEY IDENTITY,
BookingID INT NOT NULL,
Amount DECIMAL(10, 2) NOT NULL,
PaymentDate DATETIME DEFAULT GETDATE(),
PaymentMethod VARCHAR(50) NOT NULL,
);

AltER TABLE Payment
ADD CONSTRAINT FK_Payment_Booking
FOREIGN KEY (BookingID) 
REFERENCES Booking(BookingID); 
